version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    ports:
      - "8080:8080"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27018/mydb
    depends_on:
      - db

  db:
    image: mongo:4.2
    container_name: db
    ports:
      - "27018:27018"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
